## NUMPY

In [2]:
# working with arrays
# you can think of arrays as matrices
import numpy as np

In [4]:
list1=[1,2,3,4,5]

In [6]:
list1

[1, 2, 3, 4, 5]

In [8]:
# to show the type of object you created
print(type(list1))

<class 'list'>


In [10]:
mytup1=(1,2,3,4,5)

In [12]:
mytup1

(1, 2, 3, 4, 5)

In [14]:
print(type(mytup1))

<class 'tuple'>


## Converting a List into an Array

In [17]:
array1=np.array(list1)

In [19]:
array1

array([1, 2, 3, 4, 5])

In [21]:
print(type(array1))

<class 'numpy.ndarray'>


### NB:The list elements are separated by a comma. For the array, no comma.

## NUMPY Array Built-in functions

### Creating a one dimensional array

### The A-Range() function

In [37]:
# we can use the arange function to have a 1-D array with values from 1 to 10 and increment of 2
# np.arange(start,stop,step_by)

x=np.arange(1,10,2)
print(x)

[1 3 5 7 9]


### np.random.rand() function

In [42]:
# this random.rand() function generates vales from a uniform distribution
# the values are generated from an interval, (0 to 1)
y=np.random.rand(5)

print(y)

[0.64089156 0.5940402  0.51289946 0.27271426 0.41716713]


## 2-Dimensional Arrays

In [47]:
list2=[[1,2,3],
       [4,5,6],
       [7,8,9]]

In [55]:
my_matrix=np.array(list2)

In [51]:
print(my_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [53]:
print(type(my_matrix))

<class 'numpy.ndarray'>


## Using random.rand() function for 2*3 matrix

In [58]:
# np.random.rand(rows,columns) containing values from 0 to 1
z=np.random.rand(2,3)
print(z)

[[0.14999914 0.18772218 0.68454354]
 [0.50632973 0.35271172 0.4345245 ]]


In [60]:
#np.random.randn() for random values follows a standard normal distribution with mean 0 and std of 1

a=np.random.randn(5)
print(a)

[-0.28070308  2.17568234 -1.88219522  2.16315481  0.83146114]


In [62]:
#np.random.randn() for random values follows a standard normal distribution with mean 0 and std of 1

b=np.random.randn(3,3)
print(b)

[[-1.27395446  0.16294755 -0.56841838]
 [-0.16005194 -3.36024432 -0.17039972]
 [ 1.28315946 -0.29067423 -0.18024941]]


In [64]:
#np.random.randint(start,stop,(rows,columns))

c=np.random.randint(10,100,(3,4))
print(c)

[[11 63 65 39]
 [13 88 11 12]
 [16 37 11 38]]


### To know the shape of your array

In [67]:
my_matrix.shape

(3, 3)

In [69]:
z.shape

(2, 3)

In [71]:
c.shape

(3, 4)

In [73]:
b.shape

(3, 3)

## 3- D arrays

In [76]:
# a  list of list of lists
arr1=np.array([
    [
        [1,2,3],
        [4,5,6],
        [1,2,3],
        [4,5,6]
    ]
]
)


print(arr1)

[[[1 2 3]
  [4 5 6]
  [1 2 3]
  [4 5 6]]]


In [78]:
arr1.shape

(1, 4, 3)

In [80]:
# list of lists of lists
arr3=np.array([
    [
        [1,2,3],
        [4,5,6],
        [7,8,9],
        [4,5,6]
    ],
    [
        [5,6,8],
        [2,5,8],
        [3,5,1],
        [4,9,7]
        
    ],
    [
        [4,1,1],
        [1,1,1],
        [2,2,3],
        [2,5,5]
    ]
    
])

print(arr3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]
  [4 5 6]]

 [[5 6 8]
  [2 5 8]
  [3 5 1]
  [4 9 7]]

 [[4 1 1]
  [1 1 1]
  [2 2 3]
  [2 5 5]]]


In [82]:
arr3.shape

(3, 4, 3)

## Initial Place Holder in Numpy Array

### In particular cases, we may wish to initialize numpy arrays with certain values

### Creating a numpy array with all values being zero

#### np.zeros()

In [89]:
### Creating a numpy array with all values being zero

### np.zeros(rows,columns)

d=np.zeros((4,5))
print(d)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [91]:
d.shape

(4, 5)

In [93]:
# create a numpy array with all values being 1 using np.ones(rows,columns)

e=np.ones((3,4))
print(e)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [95]:
e.shape

(3, 4)

In [97]:
#array of particular values using np.full((r,c),value)

f=np.full((4,5),8)
print(f)

[[8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]]


In [99]:
f.shape

(4, 5)

In [103]:
# Creating an identity matrix i.e all the main diagonal elements will be one and the rest of the values will be zeros
# Note that identity matrices are square matrices i.e the no. of rows=no.of columns
# matrix with same number of columns and rows,in which all the diagonal are 1 and rest 0

my_identity_matrix=np.eye(4)
print(my_identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [109]:
#create an array with random values in the range 0 to 1

g=np.random.random((3,4))
print(g)

[[0.84580787 0.26753195 0.74446749 0.08636128]
 [0.83189662 0.22212378 0.89287963 0.42097632]
 [0.89231871 0.66750061 0.79827266 0.73237429]]


In [113]:
#create an array with random values in the range 0 to 1

h=np.random.randint(10,100,(3,4))
print(h)

[[31 59 55 44]
 [40 61 78 90]
 [73 12 27 52]]


## Analyzing a NUMPY Array

In [117]:
# Number of elements in an array using arr3.size function

arr3.size

36

In [119]:
h.size

12

In [121]:
# Checking for the data type of your array

arr3.dtype

dtype('int32')

In [123]:
h.dtype

dtype('int32')

In [129]:
# checking maximum values
arr3.max()

9

In [133]:
g.max()

0.8928796280695942

In [127]:
# Checking minimum values
arr3.min()

1

In [131]:
g.min()

0.08636127913908664

## Some Mathematical operations

In [136]:
m=np.random.randint(10,20,(3,3))
n=np.random.randint(20,30,(3,3))

print(m)

print("\n")
print(n)

[[18 10 10]
 [10 10 15]
 [10 15 16]]


[[21 26 20]
 [23 25 26]
 [23 20 24]]


In [138]:
m+n

array([[39, 36, 30],
       [33, 35, 41],
       [33, 35, 40]])

In [140]:
m-n

array([[ -3, -16, -10],
       [-13, -15, -11],
       [-13,  -5,  -8]])

In [142]:
m*n

array([[378, 260, 200],
       [230, 250, 390],
       [230, 300, 384]])

In [144]:
# multiplication
np.multiply(m,n)

array([[378, 260, 200],
       [230, 250, 390],
       [230, 300, 384]])

In [146]:
m/n

array([[0.85714286, 0.38461538, 0.5       ],
       [0.43478261, 0.4       , 0.57692308],
       [0.43478261, 0.75      , 0.66666667]])

In [148]:
#division
print(m/n)

[[0.85714286 0.38461538 0.5       ]
 [0.43478261 0.4        0.57692308]
 [0.43478261 0.75       0.66666667]]


In [150]:
#square root
np.sqrt(m)

array([[4.24264069, 3.16227766, 3.16227766],
       [3.16227766, 3.16227766, 3.87298335],
       [3.16227766, 3.87298335, 4.        ]])

In [152]:
#trigonometry
np.sin(n)

array([[ 0.83665564,  0.76255845,  0.91294525],
       [-0.8462204 , -0.13235175,  0.76255845],
       [-0.8462204 ,  0.91294525, -0.90557836]])

In [154]:
#logarithm
np.log(m)

array([[2.89037176, 2.30258509, 2.30258509],
       [2.30258509, 2.30258509, 2.7080502 ],
       [2.30258509, 2.7080502 , 2.77258872]])

In [156]:
#mean
arr1.mean()

3.5

In [158]:
#standard deviation
m.std()

3.0912061651652345

In [160]:
#for transpose

np.transpose(m)

array([[18, 10, 10],
       [10, 10, 15],
       [10, 15, 16]])